apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: carlosrv
  name: backenddep1555866905
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/backenddep1555866905
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: carlosrv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: carlosrv
    spec:
      containers:
      - image: 100.125.0.23:6443/carlos.ramirezv/bpnodemongo:latest
        imagePullPolicy: Always
        name: backend
        env:
        - name: MONGODB_HOST
          value: "mongo1555866905"
        - name: NM_APP_NAME
          value: "carlosrv"
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
