apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: carlosrv
  name: backendsrv1555866905
  selfLink: /api/v1/namespaces/default/services/backendsrv1555866905
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: carlosrv
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
